// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LQhpHp_n6AhI8e4Tq3L9nulxjs_xLGU',
    appId: '1:675287784625:web:06b3a18eae8cdb60011690',
    messagingSenderId: '675287784625',
    projectId: 'nosso-sindico-263f6',
    authDomain: 'nosso-sindico-263f6.firebaseapp.com',
    databaseURL: 'https://nosso-sindico-263f6-default-rtdb.firebaseio.com',
    storageBucket: 'nosso-sindico-263f6.appspot.com',
    measurementId: 'G-FJXPXZ9PJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQ6_G0lkKWeLFeaEPla3YOSaLK1phcdw',
    appId: '1:675287784625:android:5807ea5e3a92df81011690',
    messagingSenderId: '675287784625',
    projectId: 'nosso-sindico-263f6',
    databaseURL: 'https://nosso-sindico-263f6-default-rtdb.firebaseio.com',
    storageBucket: 'nosso-sindico-263f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVK-g35HNkGqaq36o4bxGf4t0-n352Is',
    appId: '1:675287784625:ios:e6db9c798ca369f6011690',
    messagingSenderId: '675287784625',
    projectId: 'nosso-sindico-263f6',
    databaseURL: 'https://nosso-sindico-263f6-default-rtdb.firebaseio.com',
    storageBucket: 'nosso-sindico-263f6.appspot.com',
    iosClientId: '675287784625-5sgt9pm710vhce428ldqhnj4h4hvq602.apps.googleusercontent.com',
    iosBundleId: 'com.example.nossosindicoApp',
  );
}
